# Generated by Django 5.1.5 on 2026-04-30 19:55

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Experience',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=200)),
                ('slug', models.SlugField(unique=True)),
                ('experience_type', models.CharField(choices=[('winery_tour', 'Tour por la Bodega'), ('premium_tasting', 'Cata Premium'), ('harvest', 'Experiencia de Vendimia'), ('private_event', 'Evento Privado'), ('wine_pairing', 'Maridaje con Chef')], max_length=30)),
                ('description', models.TextField()),
                ('duration_minutes', models.IntegerField()),
                ('price_per_person', models.DecimalField(decimal_places=2, max_digits=8)),
                ('min_guests', models.IntegerField(default=1)),
                ('max_guests', models.IntegerField()),
                ('includes', models.JSONField(blank=True, default=list)),
                ('highlights', models.JSONField(blank=True, default=list)),
                ('cover_image', models.URLField()),
                ('gallery_images', models.JSONField(blank=True, default=list)),
                ('cancellation_hours', models.IntegerField(default=48)),
                ('is_active', models.BooleanField(default=True)),
                ('is_featured', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='TimeSlot',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('start_time', models.TimeField()),
                ('end_time', models.TimeField()),
                ('capacity', models.IntegerField()),
                ('spots_available', models.IntegerField()),
                ('guide_name', models.CharField(blank=True, max_length=100)),
                ('is_blocked', models.BooleanField(default=False)),
                ('block_reason', models.CharField(blank=True, max_length=200)),
                ('experience', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='slots', to='reservations.experience')),
            ],
        ),
        migrations.CreateModel(
            name='Booking',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('confirmation_code', models.CharField(max_length=10, unique=True)),
                ('guest_count', models.IntegerField()),
                ('total_price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('status', models.CharField(choices=[('confirmed', 'Confirmada'), ('cancelled', 'Cancelada'), ('completed', 'Completada'), ('no_show', 'No se presentó')], default='confirmed', max_length=20)),
                ('special_requests', models.TextField(blank=True)),
                ('dietary_restrictions', models.JSONField(blank=True, default=list)),
                ('qr_code_url', models.URLField(blank=True)),
                ('checked_in_at', models.DateTimeField(blank=True, null=True)),
                ('reminder_24h_sent', models.BooleanField(default=False)),
                ('reminder_1h_sent', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='bookings', to=settings.AUTH_USER_MODEL)),
                ('time_slot', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='bookings', to='reservations.timeslot')),
            ],
        ),
        migrations.AddIndex(
            model_name='timeslot',
            index=models.Index(fields=['date', 'experience'], name='reservation_date_1e3de1_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='timeslot',
            unique_together={('experience', 'date', 'start_time')},
        ),
    ]
