# Generated by Django 5.1.5 on 2026-06-23 01:37

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reservations', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='booking',
            name='customer_email',
            field=models.EmailField(blank=True, max_length=254),
        ),
        migrations.AddField(
            model_name='booking',
            name='customer_first_name',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='booking',
            name='customer_last_name',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='booking',
            name='customer_phone',
            field=models.CharField(blank=True, max_length=20),
        ),
        migrations.AlterField(
            model_name='booking',
            name='status',
            field=models.CharField(choices=[('pending_payment', 'Esperando pago'), ('payment_failed', 'Pago fallido'), ('confirmed', 'Confirmada'), ('cancelled', 'Cancelada'), ('completed', 'Completada'), ('no_show', 'No se presentó')], default='pending_payment', max_length=20),
        ),
        migrations.AlterField(
            model_name='booking',
            name='user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='bookings', to=settings.AUTH_USER_MODEL),
        ),
        migrations.CreateModel(
            name='BookingPayment',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('idempotency_key', models.CharField(max_length=100, unique=True)),
                ('mp_preference_id', models.CharField(blank=True, max_length=100)),
                ('preference_init_point', models.URLField(blank=True, max_length=1000)),
                ('preference_sandbox_init_point', models.URLField(blank=True, max_length=1000)),
                ('mp_payment_id', models.CharField(blank=True, max_length=100)),
                ('mp_merchant_order_id', models.CharField(blank=True, max_length=100)),
                ('status', models.CharField(choices=[('pending', 'Pendiente'), ('approved', 'Aprobado'), ('rejected', 'Rechazado'), ('cancelled', 'Cancelado'), ('refunded', 'Reembolsado'), ('in_process', 'En proceso')], default='pending', max_length=20)),
                ('status_detail', models.CharField(blank=True, max_length=100)),
                ('payment_method', models.CharField(blank=True, max_length=50)),
                ('payment_type', models.CharField(blank=True, max_length=50)),
                ('installments', models.IntegerField(default=1)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('currency', models.CharField(default='ARS', max_length=3)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('booking', models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, related_name='payment', to='reservations.booking')),
            ],
            options={
                'constraints': [models.UniqueConstraint(condition=models.Q(('mp_preference_id', ''), _negated=True), fields=('mp_preference_id',), name='unique_nonempty_booking_mp_preference_id'), models.UniqueConstraint(condition=models.Q(('mp_payment_id', ''), _negated=True), fields=('mp_payment_id',), name='unique_nonempty_booking_mp_payment_id')],
            },
        ),
    ]
