# Generated by Django 5.1.5 on 2026-06-24 23:34

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reservations', '0002_booking_customer_email_booking_customer_first_name_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='booking',
            name='client_request_id',
            field=models.CharField(blank=True, max_length=120),
        ),
        migrations.AddField(
            model_name='booking',
            name='hold_expires_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='experience',
            name='cancellation_hours',
            field=models.IntegerField(default=24),
        ),
        migrations.AddIndex(
            model_name='booking',
            index=models.Index(fields=['status', 'hold_expires_at'], name='reservation_status_899e89_idx'),
        ),
        migrations.AddConstraint(
            model_name='booking',
            constraint=models.UniqueConstraint(condition=models.Q(('client_request_id', ''), _negated=True), fields=('client_request_id',), name='unique_nonempty_booking_client_request_id'),
        ),
    ]
