# Generated by Django 5.1.5 on 2026-06-25 00:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('automations', '0001_outboxevent'),
    ]

    operations = [
        migrations.AlterField(
            model_name='outboxevent',
            name='event_type',
            field=models.CharField(choices=[('order.email', 'Email de pedido'), ('booking.email', 'Email de reserva'), ('order.andreani', 'Despacho Andreani')], max_length=50),
        ),
    ]
