# Generated by Django 5.1.5 on 2026-05-27 21:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ai', '0001_initial'),
    ]

    operations = [
        migrations.RenameIndex(
            model_name='knowledgechunk',
            new_name='ai_knowledg_documen_901c83_idx',
            old_name='ai_knowledg_documen_6e6d84_idx',
        ),
    ]
