# Generated by Django 5.1.5 on 2026-05-27 22:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ai', '0002_rename_ai_knowledg_documen_6e6d84_idx_ai_knowledg_documen_901c83_idx'),
        ('ai', '0003_pgvector_support'),
    ]

    operations = [
    ]
