# Generated by Django 5.1.5 on 2026-05-28 03:15

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ai', '0005_operations_entities'),
        ('catalog', '0002_initial'),
        ('orders', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='supporttask',
            name='task_type',
            field=models.CharField(choices=[('support_follow_up', 'Support follow-up'), ('order_issue', 'Order issue'), ('order_review', 'Order review'), ('payment_review', 'Payment review'), ('lead_follow_up', 'Lead follow-up'), ('conversation_escalation', 'Conversation escalation'), ('restock', 'Restock'), ('shipping_claim', 'Shipping claim'), ('cancellation_review', 'Cancellation review')], max_length=50),
        ),
        migrations.CreateModel(
            name='StockReservation',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('quantity', models.PositiveIntegerField()),
                ('status', models.CharField(choices=[('active', 'Active'), ('partially_released', 'Partially released'), ('released', 'Released'), ('cancelled', 'Cancelled')], default='active', max_length=30)),
                ('reason', models.TextField(blank=True)),
                ('released_quantity', models.PositiveIntegerField(default=0)),
                ('released_at', models.DateTimeField(blank=True, null=True)),
                ('metadata', models.JSONField(blank=True, default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('conversation', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='stock_reservations', to='ai.conversation')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_stock_reservations', to=settings.AUTH_USER_MODEL)),
                ('customer', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='ai_stock_reservations', to=settings.AUTH_USER_MODEL)),
                ('order', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='ai_stock_reservations', to='orders.order')),
                ('wine', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='ai_stock_reservations', to='catalog.wine')),
                ('workflow_run', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='stock_reservations', to='ai.workflowrun')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
