# Generated by Django 5.1.5 on 2026-04-30 19:55

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('catalog', '0001_initial'),
        ('orders', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='review',
            name='order',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='orders.order'),
        ),
        migrations.AddField(
            model_name='review',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='wine',
            name='category',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='catalog.category'),
        ),
        migrations.AddField(
            model_name='wine',
            name='varietal',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='catalog.varietal'),
        ),
        migrations.AddField(
            model_name='review',
            name='wine',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reviews', to='catalog.wine'),
        ),
        migrations.AddField(
            model_name='wineimage',
            name='wine',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='images', to='catalog.wine'),
        ),
        migrations.AddIndex(
            model_name='wine',
            index=models.Index(fields=['category', 'is_active'], name='catalog_win_categor_b61892_idx'),
        ),
        migrations.AddIndex(
            model_name='wine',
            index=models.Index(fields=['varietal', 'vintage_year'], name='catalog_win_varieta_6c002c_idx'),
        ),
        migrations.AddIndex(
            model_name='wine',
            index=models.Index(fields=['price'], name='catalog_win_price_2e9ef4_idx'),
        ),
        migrations.AddConstraint(
            model_name='review',
            constraint=models.UniqueConstraint(fields=('wine', 'user', 'order'), name='unique_review_per_order'),
        ),
    ]
